import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Granite Chat AI - Conversational AI Solutions",
  description:
    "Granite Chat AI offers customizable and scalable conversational AI solutions built with Next.js and powered by Granite AI. Generated by Nanang Marvin Kurniawan.",
  keywords: [
    "conversational AI, chatbot, Next.js, Granite AI, Nanang Marvin Kurniawan, IBM Granite, AI solutions, chat application, scalable AI, customizable chatbot",
  ],
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
